---
- name: start mysql-server
  service: name=mysqld state=started
  sudo: true

- name: reload mysql-server
  service: name=mysqld state=reloaded
  sudo: true

- name: restart mysql-server
  service: name=mysqld state=restarted

- name: restart apache
  service: name=httpd state=restarted
  sudo: true

- name: reload apache
  service: name=httpd state=restarted
  sudo: true
