# This script provisions the server and should be run with root
- hosts: memoryhole
  remote_user: "{{ sys_access_user }}"
  sudo: yes

  roles:
    - geerlingguy.apache

  vars_files:
    - ../config.yml

  handlers:
    - include: handlers/main.yml

  pre_tasks:
    - include: tasks/certs.yml

  tasks:
    - include: tasks/mysql.yml
    - include: tasks/application.yml
