# This script provisions the server and should be run with root
- hosts: memoryhole
  remote_user: root
  sudo: yes

  vars_files:
    - ../cities/{{ city_key }}/config.yml

  pre_tasks:
    - include: tasks/init.yml

  handlers:
    - include: handlers/main.yml
